"""Remove batch_quantity and add recipe to tx

Revision ID: 27b8bd85645c
Revises: bcf0c5bec6d0
Create Date: 2026-08-15 13:27:44.144898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b8bd85645c'
down_revision = 'bcf0c5bec6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_uuid', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'recipes', ['recipe_uuid'], ['uuid'])

    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('productions_product_uuid_fkey'), type_='foreignkey')
        batch_op.drop_column('batch_quantity')
        batch_op.drop_column('damaged_quantity')
        batch_op.drop_column('product_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('damaged_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('batch_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('productions_product_uuid_fkey'), 'products', ['product_uuid'], ['uuid'])

    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recipe_uuid')

    # ### end Alembic commands ###
