"""Remove role and approved status

Revision ID: 3b33fd02a5fd
Revises: 69cadaf28ca4
Create Date: 2026-08-16 16:30:32.011662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b33fd02a5fd'
down_revision = '69cadaf28ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('ADMIN', 'MANAGER', 'STAFF', 'NORMAL', name='userrole'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
