"""Add order_uuid to ProductTransaction

Revision ID: 69cadaf28ca4
Revises: 27b8bd85645c
Create Date: 2026-08-15 14:18:39.221511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cadaf28ca4'
down_revision = '27b8bd85645c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_uuid', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['order_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_uuid')

    # ### end Alembic commands ###
