"""Initial migration

Revision ID: 951f3ffaa09f
Revises: 267a70f51086
Create Date: 2026-04-22 14:42:42.004448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951f3ffaa09f'
down_revision = '267a70f51086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='categorystatus'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_categories')
    # ### end Alembic commands ###
