"""add assigned_to to orders

Revision ID: bcf0c5bec6d0
Revises: fa13115e2279
Create Date: 2026-07-31 08:32:12.216932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf0c5bec6d0'
down_revision = 'fa13115e2279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
