"""add user_other_information table

Revision ID: c6434e379618
Revises: 3b33fd02a5fd
Create Date: 2026-08-18 08:40:27.969132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6434e379618'
down_revision = '3b33fd02a5fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_other_information',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('field_title', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_other_information')
    # ### end Alembic commands ###
